### ISSUE TITLE
"Split model into parts" creates empty objects

### ISSUE THREAD

**Issue by BloodyIron** [fieldOfView/Cura-MeshTools#40] opened 2024-01-08 17:25 UTC
I love this plugin, however sometimes when I split up a model into parts it creates empty objects. And some of those times it creates a lot of empty objects for "reasons".

I'm using v3.7.2 of the plugin, and this seems to happen with the same models every time, and with the models where the problem does not exist it does not happen. So the problem seems to be consistent for when it does happen.

Now I can delete the empty objects, but this is a pretty real time cost just deleting things that shouldn't have been made in the first place. And that's especially time-costly when it's literally tens (20-30+) of empty objects. Trying to delete the empty ones without deleting the actual things I just split.

Can we please get this looked at? Somehow I'm the first person to experience this...

Cura V5.5.0 on Ubuntu Linux using the AppImage version.

**Comment by fieldOfView** [comment] 2024-01-09 11:18
>  this seems to happen with the same models every time

Please post a link to a model with which this happens, so I can reproduce it and see what I can do about it.

**Comment by BloodyIron** [comment] 2024-01-09 16:31
> > this seems to happen with the same models every time
> 
> Please post a link to a model with which this happens, so I can reproduce it and see what I can do about it.

https://www.printables.com/model/605438-geared-fidget-spinner-now-with-ovaloid-gears

With the "Gears n Knobs" file I think it was.

**Comment by fieldOfView** [comment] 2024-01-11 13:51
It seems that in that case, Mesh Tools is doing nothing wrong. The model seems to have a number of duplicate/extraneous/unconnected (two-sided) faces. If you select one of the "empty" models and got to Mesh Tools -> Analyse Mesh, it will tell you that the selected mesh has 3 vertices and 2 faces, ie it is a two-sided single triangle. They are so tiny and flat that you don't get to see them unless you zoom all the way in.

A fairly easy way to remove these "empty" models (which are not empty) is to manually select the 6 gears and knobs by clicking them with the Shift key held down, and then group them. Now it is easy to use the Object list to select all the models outside the group and then delete them. Finally you can ungroup the 6 gears and knobs.

I am closing this issue, because Mesh Tools seems to be doing exactly as told.

**Closed as completed by fieldOfView** 2024-01-11 13:51 UTC
Labels: bug

**Comment by BloodyIron** [comment] 2024-01-11 18:39
Surely there's a better way to handle such disconnected aspects. There's no reasonable way to devise a "Are you sure?" or other error detection capabilities for such things? Removing the extraneous objects now and then is fine, but in this case it creates like 30 of them, each time I ever have to do any splitting (which can be more than just one instance).

**Comment by fieldOfView** [comment] 2024-01-13 21:14
> There's no reasonable way to devise a "Are you sure?" or other error detection capabilities for such things? 

I can't think of any. The model is faulty, the plugins is doing what you ask it to do with the model. You are smarter than the plugin is. For you it may be obvious what the you want the plugin to do with the model, but the plugin cannot "think", only "do".

**Comment by BloodyIron** [comment] 2024-01-14 15:56
In that example stl file, when it gets broken up like this, and you may be a better person to answer this question than myself, but... those "undesired" additional "split objects", do they form actual 3d objects, or are they floating one-sided polygons? I don't know the capabilities of Cura, but if splitting an object into multiple objects, if one of those split objects don't make an actual shape more than just 2-dimensional planes (grossly open gaps), could not that be automatically "culled" in the process and those 2d planes be dropped by the slicing process instead? I'm accounting for objects that have very small gaps in them but can still be a printable shape/object.

**Comment by fieldOfView** [comment] 2024-01-15 10:02
> do they form actual 3d objects, or are they floating one-sided polygons

In this case, they are two-sided polygons. And, in this case, they do not leave behind a small gap in the model when removed. In other cases, removing such geometry may actually cause slicing issues.

I could add an additional function to (for example) "Remove minuscule models", but this would be an additional step after "Split models". It would be up to the user to check if removing these minuscule models wouldn't actually cause problems.

**Comment by BloodyIron** [comment] 2024-01-15 19:47
I think the second step could hypothetically work, at least for me from a UX perspective. As for in-practice, well... I'm still teh newb to 3d printing :P
